steps:
  # Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Build frontend
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "frontend"

options:
  logging: CLOUD_LOGGING_ONLY
